### ISSUE TITLE
Running app_springboot.jar in a container

### ISSUE THREAD

**Issue by mtsgrd** [salesforce/bazel-springboot-rule#1]
First and foremost, many thanks for publishing these rules.

I'm trying to run the output jar in a container, and am running into the following error when Spring serves static content.

```
java.io.FileNotFoundException: class path resource [static/index.html] cannot be resolved in the file system for resolving its last-modified timestamp
	at org.springframework.core.io.AbstractResource.lastModified(AbstractResource.java:155) ~[spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.core.io.AbstractFileResolvingResource.lastModified(AbstractFileResolvingResource.java:169) ~[spring-core-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
```
Looking at the Spring source, [I found this section](https://github.com/spring-projects/spring-framework/blob/73cf07e9a4f1000087118c24ef5d56f621f41160/spring-core/src/main/java/org/springframework/core/io/AbstractResource.java#L173) in `AbstractResource.java`.

```java
if (lastModified == 0L) {
  throw new FileNotFoundException(getDescription() +
      " cannot be resolved in the file system for resolving its last-modified timestamp");
}
```
I assume this is tripped because Bazel wants deterministic builds and sets file timestamps to zero. Does anyone know how to work around this?

**Comment by oferb** [comment]
@mtsgrd Did you end up resolving this?

**Comment by mtsgrd** [comment]
Yes, I just used another class for loading resources. I can't say how to solve it for functionality that depends on `AbstractResrouce.java`..
