### ISSUE TITLE
Update documentation to show how to reference this rule 

### ISSUE THREAD

**Issue by simontoens** [salesforce/bazel-springboot-rule#21]
The documentation says this rule should be copied.  However, it can referenced as a remote repository, using `git_repository`, which is nicer than copying.

**Comment by plaird** [comment]
Until we get to this doc, this is what we use internally:

**WORKSPACE**

git_repository(
    name = "bazel_springboot_rule",
    remote = "https://github.com/salesforce/bazel-springboot-rule.git",
    commit = "ed5908c25487cd5806a5583006864cde8cf312a3"
)

**BUILD**

load("@bazel_springboot_rule//tools/springboot:springboot.bzl", "springboot")

springboot(
    name = "helloworld",
    boot_app_class = "com.salesforce.helloworld.HelloWorld",
    fail_on_duplicate_classes = True,
    java_library = ":base_lib",
    deps = deps,
)

deps = [...]

java_library(
    name = "base_lib",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    deps = deps,
)

**Comment by plaird** [comment]
This was written into our docs here: https://github.com/salesforce/bazel-springboot-rule/tree/master/tools/springboot#add-the-rule-to-your-workspace
