### ISSUE TITLE
SpringBoot rule should pull through deps and runtime_deps from java_library

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-springboot-rule#31]
Given my base lib definition here:

```
java_library(
    name = "base_lib",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    deps = deps,
    runtime_deps = runtime_deps,
)
```

I have to construct the deps attribute for my springboot rule invocation like this:

```
springboot(
    name = "test-service",
    boot_app_class = "com.salesforce.services.test.TestServiceMain",
    java_library = ":base_lib",
    deps = deps + runtime_deps,
)
```

I shouldn't have to provide the **deps** or **runtime_deps** in the deps attribute, the rule should do that automatically.

**Comment by yishanhe** [comment]
should the springboot rule also exposes only runtime_deps instead of deps?

**Comment by plaird** [comment]
@yishanhe are you consuming the output of springboot rule somehow? for us, the springboot rule is always a terminal node in the dependency graph.

**Comment by yishanhe** [comment]
@plaird , Thank you for your explain, and It is great to see this one gets improved. 

A follow-up question, would it be clear if we put the deps in this way in this way

```
java_library(
    name = "helloworld_lib",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    deps = lib_deps,
    runtime_deps = springboot_deps,
)

springboot(
    name = "helloworld",
    boot_app_class = "com.sample.SampleMain",
    java_library = ":helloworld_lib",
    # NO DEPS NEED TO BE DECLARED HERE
)
```

Thanks

**Comment by plaird** [comment]
Yes, I can add the comment to the example, that will make it more clear. Thanks for the feedback.
