### ISSUE TITLE
Support for Bazel 3.2 on Windows

### ISSUE THREAD

**Issue by omathias** [salesforce/bazel-springboot-rule#38]
Hello Everyone,

Does this support Bazel 3.2 on Windows.

Thanks, Oliver

**Comment by plaird** [comment]
There will need to be a fix for 3.x, as we currently have a flag set  --incompatible_depset_union=false and that is not available in 3.x. But that shouldn't be too hard to fix.

Windows support is a bigger issue as this rule is written with Bash. Issue #25 tracks Windows support and I have no estimate on when we will have that.

**Comment by plaird** [comment]
Closing as a dupe for #25
