### ISSUE TITLE
BOOT-INF/lib jars are pathed using Bazel internal directory structures

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-springboot-rule#61]
Dependency jars should be nested directly under BOOT-INF/lib. But currently we are constructing the spring boot jar with internal details of the build in the form of deeply nested path structures. Spring Boot seems to be able to handle it, but it is poor form.

For maven_install deps, we see paths like:
_BOOT-INF/lib/bazel-out/darwin-fastbuild/bin/external/maven/v1/https/nexus-proxy-prd.soma.salesforce.com/nexus/content/groups/public/com/fasterxml/jackson/core/jackson-annotations/2.10.5/jackson-annotations-2.10.5.jar_

For internal deps, we see paths like:
_BOOT-INF/lib/bazel-out/darwin-fastbuild/bin/projects/libs/acme/blue_lib/liblue_lib.jar_

**Comment by simontoens** [comment]
@plaird we will have to be careful to handle duplicate names, since there can be targets with the same name under different packages.  Not an issue, for jars coming from Nexus. Perhaps for internal deps we just keep the root repo path to guarantee uniqueness?

**Comment by plaird** [comment]
Good point @simontoens perhaps we just trim the 'bazel-out/darwin-fastbuild/bin' segment from the path for internal deps.

**Comment by plaird** [comment]
While the algorithm isn't full proof, in most cases the jars in BOOT-INF/lib will now be cleaner. See the PR for more details.
